### ISSUE TITLE
Not Import Error

### ISSUE THREAD

**Issue by minseong-alchera** [jbohnslav/opencv_transforms#10]
https://github.com/jbohnslav/opencv_transforms/blob/f197a7c0740d03e4b037a7110955e88754f355b0/opencv_transforms/functional.py#L375

https://github.com/jbohnslav/opencv_transforms/blob/f197a7c0740d03e4b037a7110955e88754f355b0/opencv_transforms/functional.py#L376

**Image** and **ImageEnhance** is not imported in functional.py

**Comment by jbohnslav** [comment]
Fixed with 0e4962d.
