### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by victorca25** [jbohnslav/opencv_transforms#16]
This is not an issue, just to let you know I've commited an update to my fork of your repo, that I combined with https://github.com/YU-Zhiyang/opencv_transforms_torchvision and additional augmentations using OpenCV from one of my repos.

I tried to keep the best from all sources, use only OpenCV or np functions and extend functionality where possible, like the resample flag on RandomRotation.

In case you are interested, here's the repo: https://github.com/victorca25/opencv_transforms should be able to easily pull from it, since I kept it as a fork.

**Comment by jbohnslav** [comment]
Thank you!
